=== hemilabs/blockscout-config/schemas/marketplace-config.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "items": {
    "additionalProperties": false,
    "properties": {
      "author": { "type": "string" },
      "categories": { "items": { "type": "string" }, "type": "array" },
      "description": { "type": "string" },
      "external": { "type": "boolean" },
      "github": { "format": "uri", "type": "string" },
      "id": { "type": "string" },
      "internalWallet": { "type": "boolean" },
      "logo": { "format": "uri", "type": "string" },
      "priority": { "type": "number" },
      "shortDescription": { "type": "string" },
      "site": { "format": "uri", "type": "string" },
      "telegram": { "format": "uri", "type": "string" },
      "title": { "type": "string" },
      "twitter": { "format": "uri", "type": "string" },
      "url": { "format": "uri", "type": "string" }
    },
    "required": [
      "author",
      "categories",
      "description",
      "id",
      "logo",
      "shortDescription",
      "title",
      "url"
    ],
    "type": "object"
  },
  "type": "array"
}

=== hemilabs/blockscout-config/marketplace/config.json
[{
  "id": "demos",
  "external": true,
  "title":"Demos",
  "logo": "https://2715296027-files.gitbook.io/~/files/v0/b/gitbook-x-prod.appspot.com/o/spaces%2FxZnkmJ00s3wgxLckYeeU%2Fuploads%2FVfSH1jvjvoVvgckTL3J5%2FDemosLogo1.2.svg?alt=media",
  "shortDescription": "Enhanced Web3 security with intuitive and robust Sybil resistance solutions.",
  "categories": ["Dev Tooling", "Data & Analytics"],
  "author": "Demos",
  "url": "https://app.demos.gloabl",
  "description": "Enhanced Web3 security with intuitive and robust Sybil resistance solutions.",
  "site": "https://www.demos.global"
}]
